import { Award, Office, UserProfile, Application, ApplicationHistory, InAppNotification } from '../types';

export const INITIAL_OFFICES: Office[] = [
  { id: 'off-1', name: 'City Mayor\'s Office', code: 'CMO', head_name: 'Hon. Alfred S. Romualdez', head_title: 'City Mayor', is_active: true },
  { id: 'off-2', name: 'City Administrator\'s Office', code: 'CAO', head_name: 'Atty. Irene V. Chiu', head_title: 'City Administrator', is_active: true },
  { id: 'off-3', name: 'Human Resource Management and Development Office', code: 'HRMDO', head_name: 'Marites S. Bocar', head_title: 'City Government Department Head II', is_active: true },
  { id: 'off-4', name: 'City Health Office', code: 'CHO', head_name: 'Dr. Danilo E. Ecarma', head_title: 'City Health Officer II', is_active: true },
  { id: 'off-5', name: 'City Social Welfare and Development Office', code: 'CSWDO', head_name: 'Carmela S. Bastes', head_title: 'City Government Department Head II', is_active: true },
  { id: 'off-6', name: 'City Planning and Development Office', code: 'CPDO', head_name: 'Engr. Manuel C. Tan', head_title: 'City Planning Officer', is_active: true },
  { id: 'off-7', name: 'City Disaster Risk Reduction and Management Office', code: 'CDRRMO', head_name: 'Ilden T. Perez', head_title: 'CDRRMO Officer', is_active: true },
  { id: 'off-8', name: 'City General Services Office', code: 'CGSO', head_name: 'Rolando M. Gomez', head_title: 'City General Services Officer', is_active: true },
  { id: 'off-9', name: 'City Engineering Office', code: 'CEO', head_name: 'Engr. Dionisio C. De Paz', head_title: 'City Engineer', is_active: true },
  { id: 'off-10', name: 'City Treasurer\'s Office', code: 'CTO', head_name: 'Zenaida A. Santos', head_title: 'City Treasurer', is_active: true },
  { id: 'off-11', name: 'City Agriculture Office', code: 'CAO-AGRI', head_name: 'Rommel L. Almirante', head_title: 'City Agriculturist', is_active: true },
  { id: 'off-12', name: 'City Nutrition & Barangay Health Affairs', code: 'CNBHA', head_name: 'Dr. Gloria F. Fabrigas', head_title: 'City Action Officer', is_active: true },
];

export const INITIAL_AWARDS: Award[] = [
  {
    id: 'award-1',
    name: 'Outstanding Work Performance Award',
    code: 'OWPA',
    description: 'Conferred to employees who demonstrated exemplary efficiency, dedication, and exceptional accomplishments exceeding regular performance targets.',
    award_year: 2026,
    min_qualifying_score: 85,
    is_active: true,
    eligibility_requirements: [
      { id: 'el-1-1', award_id: 'award-1', requirement_description: 'Must have at least two (2) consecutive Very Satisfactory (VS) or Outstanding (O) IPCR ratings in the last two rating periods.', is_mandatory: true, order_index: 1 },
      { id: 'el-1-2', award_id: 'award-1', requirement_description: 'Must have rendered at least two (2) continuous years of service in the City Government of Tacloban.', is_mandatory: true, order_index: 2 },
      { id: 'el-1-3', award_id: 'award-1', requirement_description: 'Has not been found guilty of any administrative or criminal offense.', is_mandatory: true, order_index: 3 },
    ],
    document_requirements: [
      { id: 'doc-1-1', award_id: 'award-1', document_name: 'Accomplished PRAISE Nomination Form (Form A-1)', description: 'Signed and certified by nominator and nominee', is_mandatory: true },
      { id: 'doc-1-2', award_id: 'award-1', document_name: 'Certified Copy of IPCR for last 2 rating periods', description: 'Certified true copy from HRMDO records', is_mandatory: true },
      { id: 'doc-1-3', award_id: 'award-1', document_name: 'Head of Office Endorsement & Justification Letter', description: 'Official memo from Department Head', is_mandatory: true },
      { id: 'doc-1-4', award_id: 'award-1', document_name: 'Certificates of Recognition / Accomplishment Portfolios', description: 'Proof of projects, client commendations, or innovations', is_mandatory: false },
      { id: 'doc-1-5', award_id: 'award-1', document_name: 'HRMDO Certificate of No Pending Administrative Case', description: 'Issued within the current nomination year', is_mandatory: true },
    ],
    criteria: [
      { id: 'crit-1-1', award_id: 'award-1', criterion_name: 'Quality and Consistency of Work', criterion_description: 'Accuracy, thoroughness, adherence to LGU standards, and sustained excellence', weight_percentage: 30, max_score: 100 },
      { id: 'crit-1-2', award_id: 'award-1', criterion_name: 'Productivity and Impact to City Operations', criterion_description: 'Volume of work accomplished, delivery speed, and tangible service improvements for Taclobanons', weight_percentage: 25, max_score: 100 },
      { id: 'crit-1-3', award_id: 'award-1', criterion_name: 'Initiative, Resourcefulness & Innovation', criterion_description: 'Proactiveness in solving problems, cost-saving measures, and modern process improvements', weight_percentage: 20, max_score: 100 },
      { id: 'crit-1-4', award_id: 'award-1', criterion_name: 'Customer Service & Citizen Satisfaction', criterion_description: 'Responsiveness, courtesy, and feedback from internal and external stakeholders', weight_percentage: 15, max_score: 100 },
      { id: 'crit-1-5', award_id: 'award-1', criterion_name: 'Teamwork & Public Service Ethics (RA 6713)', criterion_description: 'Collaboration, integrity, professionalism, and adherence to Civil Service Code of Conduct', weight_percentage: 10, max_score: 100 },
    ]
  },
  {
    id: 'award-2',
    name: 'Perfect Attendance & Punctuality Award',
    code: 'PAPA',
    description: 'Recognizes regular and casual personnel with impeccable punctuality, flawless Daily Time Records (DTR), and zero unexcused tardiness or absences.',
    award_year: 2026,
    min_qualifying_score: 90,
    is_active: true,
    eligibility_requirements: [
      { id: 'el-2-1', award_id: 'award-2', requirement_description: 'Zero (0) unauthorized leaves and zero (0) tardiness or undertime for 12 continuous months.', is_mandatory: true, order_index: 1 },
      { id: 'el-2-2', award_id: 'award-2', requirement_description: 'Has not incurred more than the mandatory mandatory 5-day forced leave entitlement.', is_mandatory: true, order_index: 2 },
      { id: 'el-2-3', award_id: 'award-2', requirement_description: 'Active employee in good standing with positive performance rating.', is_mandatory: true, order_index: 3 },
    ],
    document_requirements: [
      { id: 'doc-2-1', award_id: 'award-2', document_name: 'Accomplished Nomination Form with DTR Summary', description: 'Certified by immediate supervisor', is_mandatory: true },
      { id: 'doc-2-2', award_id: 'award-2', document_name: 'HRMDO Biometric Attendance Certification (12 Months)', description: 'Official biometric logs authenticated by HRMDO Timekeeping', is_mandatory: true },
      { id: 'doc-2-3', award_id: 'award-2', document_name: 'Certificate of Leave Balances and Usage', description: 'HRMDO Leave Section Certification', is_mandatory: true },
    ],
    criteria: [
      { id: 'crit-2-1', award_id: 'award-2', criterion_name: 'Biometric Punctuality and Zero Tardiness Index', criterion_description: 'Total adherence to official work hours (8:00 AM - 5:00 PM) without late punch-ins', weight_percentage: 40, max_score: 100 },
      { id: 'crit-2-2', award_id: 'award-2', criterion_name: 'Full Workday Attendance & Zero Undertime', criterion_description: 'Consistent physical/official presence and complete shift fulfillment', weight_percentage: 35, max_score: 100 },
      { id: 'crit-2-3', award_id: 'award-2', criterion_name: 'Promptness in Flag Ceremonies and Official City Events', criterion_description: 'Regular presence and leadership in Monday Convocation and citywide civic gatherings', weight_percentage: 15, max_score: 100 },
      { id: 'crit-2-4', award_id: 'award-2', criterion_name: 'Supervisor Commendation on Dependability', criterion_description: 'Peer and supervisory validation of steady availability during crucial deadlines', weight_percentage: 10, max_score: 100 },
    ]
  },
  {
    id: 'award-3',
    name: 'On-the-Spot Heroism & Civic Duty Award',
    code: 'OSPA',
    description: 'Granted immediately to LGU personnel who showed extraordinary courage, honesty, life-saving acts, or integrity in the line of duty.',
    award_year: 2026,
    min_qualifying_score: 80,
    is_active: true,
    eligibility_requirements: [
      { id: 'el-3-1', award_id: 'award-3', requirement_description: 'Incident or remarkable civic act occurred within the current or preceding calendar quarter.', is_mandatory: true, order_index: 1 },
      { id: 'el-3-2', award_id: 'award-3', requirement_description: 'Act demonstrated exceptional honesty, risk to personal safety, or extraordinary compassion for citizens.', is_mandatory: true, order_index: 2 },
    ],
    document_requirements: [
      { id: 'doc-3-1', award_id: 'award-3', document_name: 'Incident Narrative Report & Official Blotter/Documentation', description: 'Detailed account of the heroic or honest deed', is_mandatory: true },
      { id: 'doc-3-2', award_id: 'award-3', document_name: 'Witness Statements or Client Commendation Letters', description: 'Sworn statement or letter from assisted citizen / supervisor', is_mandatory: true },
      { id: 'doc-3-3', award_id: 'award-3', document_name: 'Photographic / Media / CCTV Evidence where available', description: 'Supporting media or visual proof of the event', is_mandatory: false },
    ],
    criteria: [
      { id: 'crit-3-1', award_id: 'award-3', criterion_name: 'Magnitude and Exceptional Nature of the Act', criterion_description: 'Significance, life-saving impact, or extraordinary moral courage demonstrated', weight_percentage: 40, max_score: 100 },
      { id: 'crit-3-2', award_id: 'award-3', criterion_name: 'Integrity and Adherence to Public Accountability', criterion_description: 'Honesty (e.g. returning valuables, resisting bribery) and ethical pride', weight_percentage: 30, max_score: 100 },
      { id: 'crit-3-3', award_id: 'award-3', criterion_name: 'Positive Image and PR for the City Government', criterion_description: 'Public acclaim, community inspiration, and uplifting Tacloban City reputation', weight_percentage: 20, max_score: 100 },
      { id: 'crit-3-4', award_id: 'award-3', criterion_name: 'Immediate Verification & Credibility of Testimony', criterion_description: 'Corroboration by independent witnesses or official city blotter', weight_percentage: 10, max_score: 100 },
    ]
  },
  {
    id: 'award-4',
    name: 'Best Barangay Service Point Officer (BSPO)',
    code: 'BSPO-A',
    description: 'Recognizes outstanding BSPO volunteer workers across Tacloban’s 138 barangays for exemplary population data collection, family planning advocacy, and grassroots social mobilization.',
    award_year: 2026,
    min_qualifying_score: 85,
    is_active: true,
    eligibility_requirements: [
      { id: 'el-4-1', award_id: 'award-4', requirement_description: 'Must be an active, recognized BSPO serving a Tacloban City barangay for at least two (2) continuous years.', is_mandatory: true, order_index: 1 },
      { id: 'el-4-2', award_id: 'award-4', requirement_description: 'Endorsed by both the Punong Barangay and the City Population / CSWDO Coordinator.', is_mandatory: true, order_index: 2 },
      { id: 'el-4-3', award_id: 'award-4', requirement_description: 'Submitted 100% of required monthly family planning and demographic profiling reports on time.', is_mandatory: true, order_index: 3 },
    ],
    document_requirements: [
      { id: 'doc-4-1', award_id: 'award-4', document_name: 'Official BSPO Nomination & Accomplishment Dossier', description: 'Endorsed by Punong Barangay and CSWDO Officer', is_mandatory: true },
      { id: 'doc-4-2', award_id: 'award-4', document_name: 'Barangay Council Resolution of Endorsement', description: 'Signed by Barangay Captain and Council Members', is_mandatory: true },
      { id: 'doc-4-3', award_id: 'award-4', document_name: 'Summary of Household Profiling and Outreach Data', description: 'Certified demographic survey figures and referral logs', is_mandatory: true },
      { id: 'doc-4-4', award_id: 'award-4', document_name: 'Photo Documentation of Barangay Assemblies and Missions', description: 'Visual records of outreach in the designated zone', is_mandatory: false },
    ],
    criteria: [
      { id: 'crit-4-1', award_id: 'award-4', criterion_name: 'Household Profiling Accuracy and Coverage Rate', criterion_description: 'Percentage of households mapped, registry completeness, and data fidelity', weight_percentage: 30, max_score: 100 },
      { id: 'crit-4-2', award_id: 'award-4', criterion_name: 'Responsible Parenthood & Family Planning Advocacy', criterion_description: 'Number of counseling sessions conducted, modern FP referrals, and youth education', weight_percentage: 25, max_score: 100 },
      { id: 'crit-4-3', award_id: 'award-4', criterion_name: 'Timeliness and Quality of Monthly Reports', criterion_description: 'Prompt submission to City Population Office without deficiencies', weight_percentage: 20, max_score: 100 },
      { id: 'crit-4-4', award_id: 'award-4', criterion_name: 'Community Engagement and Mobilization in Barangay', criterion_description: 'Active leadership during barangay assemblies and disaster assistance', weight_percentage: 15, max_score: 100 },
      { id: 'crit-4-5', award_id: 'award-4', criterion_name: 'Dedication and Volunteer Spirit', criterion_description: 'Voluntary initiative beyond standard expectations and positive rapport with residents', weight_percentage: 10, max_score: 100 },
    ]
  },
  {
    id: 'award-5',
    name: 'Outstanding Barangay Nutrition Scholar (BNS)',
    code: 'BNS-A',
    description: 'Celebrates dedicated BNS volunteers who achieved remarkable gains in reducing child malnutrition, managing Operation Timbang (OPT) Plus, and leading community feeding programs.',
    award_year: 2026,
    min_qualifying_score: 85,
    is_active: true,
    eligibility_requirements: [
      { id: 'el-5-1', award_id: 'award-5', requirement_description: 'Accredited BNS in active service in Tacloban City for at least two (2) consecutive years.', is_mandatory: true, order_index: 1 },
      { id: 'el-5-2', award_id: 'award-5', requirement_description: 'Achieved at least 95% Operation Timbang (OPT) Plus coverage rate in assigned barangay.', is_mandatory: true, order_index: 2 },
      { id: 'el-5-3', award_id: 'award-5', requirement_description: 'Demonstrated documented reduction in wasted/underweight children over the past 12 months.', is_mandatory: true, order_index: 3 },
    ],
    document_requirements: [
      { id: 'doc-5-1', award_id: 'award-5', document_name: 'Accomplished BNS Evaluation Form with City Nutrition Validation', description: 'Certified by City Nutrition Action Officer (CNAO)', is_mandatory: true },
      { id: 'doc-5-2', award_id: 'award-5', document_name: 'Certified OPT Plus Annual Results and Masterlist', description: 'Validated by City Health Office Nutrition Section', is_mandatory: true },
      { id: 'doc-5-3', award_id: 'award-5', document_name: 'Barangay Nutrition Action Plan (BNAP) Implementation Report', description: 'Approved by Barangay Nutrition Committee', is_mandatory: true },
      { id: 'doc-5-4', award_id: 'award-5', document_name: 'Documentary Portfolio of Supplementary Feeding & Gulayan sa Barangay', description: 'Photos, attendance sheets, weight monitoring charts', is_mandatory: false },
    ],
    criteria: [
      { id: 'crit-5-1', award_id: 'award-5', criterion_name: 'Operation Timbang (OPT) Plus Coverage & Malnutrition Reduction', criterion_description: 'Completeness of child growth monitoring and statistical decline in underweight/stunting', weight_percentage: 35, max_score: 100 },
      { id: 'crit-5-2', award_id: 'award-5', criterion_name: 'Supplementary Feeding and Dietary Intervention Management', criterion_description: 'Quality, cleanliness, recipe variety, and weight rehabilitation success', weight_percentage: 25, max_score: 100 },
      { id: 'crit-5-3', award_id: 'award-5', criterion_name: 'Barangay Nutrition Committee Leadership & BNAP Integration', criterion_description: 'Advocacy for barangay budget allocation for nutrition and BNS honorarium', weight_percentage: 20, max_score: 100 },
      { id: 'crit-5-4', award_id: 'award-5', criterion_name: 'Gulayan sa Barangay and Food Security Initiatives', criterion_description: 'Establishment of communal vegetable gardens and home gardening advocacy', weight_percentage: 10, max_score: 100 },
      { id: 'crit-5-5', award_id: 'award-5', criterion_name: 'Nutrition Education for Mothers & Caregivers', criterion_description: 'Pabasa sa Nutrisyon sessions and infant/young child feeding (IYCF) counseling', weight_percentage: 10, max_score: 100 },
    ]
  },
  {
    id: 'award-6',
    name: 'Outstanding Barangay Health Worker (BHW)',
    code: 'BHW-A',
    description: 'Honors exemplary Barangay Health Workers serving on the frontline of primary healthcare delivery, maternal care, routine immunization, and disease surveillance in Tacloban.',
    award_year: 2026,
    min_qualifying_score: 85,
    is_active: true,
    eligibility_requirements: [
      { id: 'el-6-1', award_id: 'award-6', requirement_description: 'Registered and accredited BHW actively serving in a Tacloban City health center for at least 3 years.', is_mandatory: true, order_index: 1 },
      { id: 'el-6-2', award_id: 'award-6', requirement_description: 'Consistently achieved target immunization and prenatal monitoring quotas in assigned catchment zone.', is_mandatory: true, order_index: 2 },
      { id: 'el-6-3', award_id: 'award-6', requirement_description: 'Endorsed by both the Rural Health Physician / City Health Officer and the Punong Barangay.', is_mandatory: true, order_index: 3 },
    ],
    document_requirements: [
      { id: 'doc-6-1', award_id: 'award-6', document_name: 'Nomination Dossier with BHW Federation Accreditation', description: 'Endorsed by City Health Officer II', is_mandatory: true },
      { id: 'doc-6-2', award_id: 'award-6', document_name: 'Barangay Health Center Catchment Performance Metrics', description: 'Immunization, prenatal, TB-DOTS, and senior citizen health logs', is_mandatory: true },
      { id: 'doc-6-3', award_id: 'award-6', document_name: 'Barangay Council Resolution of Commendation', description: 'Passed by Sangguniang Barangay', is_mandatory: true },
      { id: 'doc-6-4', award_id: 'award-6', document_name: 'Certificates of Training & Health Campaign Portfolios', description: 'First aid, disease surveillance, and emergency response seminars', is_mandatory: false },
    ],
    criteria: [
      { id: 'crit-6-1', award_id: 'award-6', criterion_name: 'Primary Healthcare Delivery & Catchment Health Metrics', criterion_description: 'Immunization coverage, prenatal/postnatal tracking, TB-DOTS compliance, and vitals recording', weight_percentage: 35, max_score: 100 },
      { id: 'crit-6-2', award_id: 'award-6', criterion_name: 'Emergency Response, Disease Surveillance & Epidemic Alert', criterion_description: 'Dengue/measles reporting, swift disaster health mobilization, and first-aid readiness', weight_percentage: 25, max_score: 100 },
      { id: 'crit-6-3', award_id: 'award-6', criterion_name: 'Community Trust, Compassion & Patient Advocacy', criterion_description: 'Rapport with indigent families, bedside empathy, and continuous house visits', weight_percentage: 20, max_score: 100 },
      { id: 'crit-6-4', award_id: 'award-6', criterion_name: 'Health Center Maintenance & Inventory Management', criterion_description: 'Proper upkeep of medicine inventory, patient logbooks, and cold chain supplies', weight_percentage: 10, max_score: 100 },
      { id: 'crit-6-5', award_id: 'award-6', criterion_name: 'Attendance in Continuous Medical Education and Drills', criterion_description: 'Active participation in CHO refresher workshops, CPR training, and drills', weight_percentage: 10, max_score: 100 },
    ]
  }
];

export const INITIAL_USERS: UserProfile[] = [
  {
    id: 'user-admin-1',
    email: 'admin.hrmdo@tacloban.gov.ph',
    full_name: 'Marites S. Bocar',
    role: 'ADMINISTRATOR',
    office_id: 'off-3',
    office_name: 'Human Resource Management and Development Office',
    position_title: 'City Government Department Head II / PRAISE Focal',
    employee_id: 'TAC-HR-001',
    contact_number: '+63 917 555 1201',
    barangay: 'Brgy. 54-A Magallanes',
    created_at: '2026-01-10T08:00:00Z'
  },
  {
    id: 'user-secretariat-1',
    email: 'secretariat.praise@tacloban.gov.ph',
    full_name: 'Atty. Paul Vincent G. Yu',
    role: 'SECRETARIAT',
    office_id: 'off-3',
    office_name: 'Human Resource Management and Development Office',
    position_title: 'PRAISE Secretariat Lead / HR Officer IV',
    employee_id: 'TAC-HR-004',
    contact_number: '+63 918 222 4433',
    barangay: 'Brgy. 88 San Jose',
    created_at: '2026-01-12T09:30:00Z'
  },
  {
    id: 'user-head-1',
    email: 'cho.head@tacloban.gov.ph',
    full_name: 'Dr. Danilo E. Ecarma',
    role: 'HEAD_OF_OFFICE',
    office_id: 'off-4',
    office_name: 'City Health Office',
    position_title: 'City Health Officer II',
    employee_id: 'TAC-CHO-001',
    contact_number: '+63 919 333 8877',
    barangay: 'Brgy. 74 Nula-Tula',
    created_at: '2026-01-15T10:00:00Z'
  },
  {
    id: 'user-evaluator-1',
    email: 'evaluator.tan@tacloban.gov.ph',
    full_name: 'Engr. Manuel C. Tan',
    role: 'EVALUATOR',
    office_id: 'off-6',
    office_name: 'City Planning and Development Office',
    position_title: 'PRAISE Committee Member / Planning Officer',
    employee_id: 'TAC-CPDO-001',
    contact_number: '+63 920 444 9911',
    barangay: 'Brgy. 99 Diit',
    created_at: '2026-01-18T11:00:00Z'
  },
  {
    id: 'user-evaluator-2',
    email: 'evaluator.bastes@tacloban.gov.ph',
    full_name: 'Carmela S. Bastes',
    role: 'EVALUATOR',
    office_id: 'off-5',
    office_name: 'City Social Welfare and Development Office',
    position_title: 'PRAISE Committee Evaluator / CSWDO Head',
    employee_id: 'TAC-CSWDO-001',
    contact_number: '+63 917 888 2244',
    barangay: 'Brgy. 62-B Sagkahan',
    created_at: '2026-01-18T11:30:00Z'
  },
  {
    id: 'user-nominee-1',
    email: 'elena.rodriguez@tacloban.gov.ph',
    full_name: 'Elena M. Rodriguez',
    role: 'NOMINEE',
    office_id: 'off-4',
    office_name: 'City Health Office',
    position_title: 'Lead Barangay Health Worker',
    employee_id: 'TAC-BHW-042',
    contact_number: '+63 927 890 1234',
    barangay: 'Brgy. 83-A San Jose (Cura)',
    created_at: '2026-02-01T08:15:00Z'
  },
  {
    id: 'user-nominee-2',
    email: 'ricardo.montejo@tacloban.gov.ph',
    full_name: 'Ricardo S. Montejo',
    role: 'NOMINEE',
    office_id: 'off-7',
    office_name: 'City Disaster Risk Reduction and Management Office',
    position_title: 'Emergency Operations Center Specialist',
    employee_id: 'TAC-DRRM-019',
    contact_number: '+63 908 765 4321',
    barangay: 'Brgy. 37 Palanog',
    created_at: '2026-02-03T09:00:00Z'
  }
];

export const INITIAL_APPLICATIONS: Application[] = [
  {
    id: 'app-001',
    application_number: 'PRAISE-2026-00001',
    award_id: 'award-6',
    award_name: 'Outstanding Barangay Health Worker (BHW)',
    award_year: 2026,
    nominee_id: 'user-nominee-1',
    nominee_name: 'Elena M. Rodriguez',
    employee_id: 'TAC-BHW-042',
    position_title: 'Lead Barangay Health Worker',
    office_id: 'off-4',
    office_name: 'City Health Office',
    division_section: 'Barangay Health Services Unit',
    employment_category: 'Barangay Worker',
    contact_number: '+63 927 890 1234',
    email: 'elena.rodriguez@tacloban.gov.ph',
    barangay: 'Brgy. 83-A San Jose (Cura)',
    nomination_type: 'Individual',
    nominator_id: 'user-head-1',
    nominator_name: 'Dr. Danilo E. Ecarma',
    nominator_position: 'City Health Officer II',
    nominating_office: 'City Health Office',
    justification: 'Elena has served Brgy. 83-A for 9 straight years, reaching 99.4% child immunization coverage and conducting over 420 home wellness visits during the recent surge.',
    accomplishments: 'Pioneered the Mobile Immunization Cart in coastal sitios; achieved zero maternal mortality in her catchment zone for 3 consecutive years; organized 18 health education sessions for pregnant mothers.',
    supporting_narrative: 'Her relentless devotion to the grassroots health of Taclobanons exemplifies the highest ideals of civil service. Even during severe typhoons, she safeguarded vaccine cold storage with extreme diligence.',
    date_of_nomination: '2026-02-10',
    status: 'Evaluation Completed',
    processing_stage: 'Deliberation',
    required_action: 'Ready for PRAISE Committee Deliberation and Final Resolution',
    final_weighted_score: 95.5,
    created_at: '2026-02-10T09:00:00Z',
    updated_at: '2026-02-16T14:30:00Z',
    documents: [
      {
        id: 'doc-app-1-1',
        application_id: 'app-001',
        requirement_id: 'doc-6-1',
        document_name: 'Nomination Dossier with BHW Federation Accreditation.pdf',
        file_url: 'https://supabase-storage-placeholder/praise-documents/app-001/nomination_dossier.pdf',
        file_size: 2450000,
        file_type: 'application/pdf',
        status: 'Verified',
        verification_remarks: 'All signatures verified against CHO personnel register.',
        verified_by: 'Atty. Paul Vincent G. Yu (Secretariat)',
        verified_at: '2026-02-12T11:20:00Z',
        uploaded_at: '2026-02-10T09:15:00Z'
      },
      {
        id: 'doc-app-1-2',
        application_id: 'app-001',
        requirement_id: 'doc-6-2',
        document_name: 'Barangay Health Center Catchment Performance Metrics.pdf',
        file_url: 'https://supabase-storage-placeholder/praise-documents/app-001/performance_metrics.pdf',
        file_size: 1890000,
        file_type: 'application/pdf',
        status: 'Verified',
        verification_remarks: 'Complete 12-month records validated with CHO Epidemiological Surveillance Unit.',
        verified_by: 'Atty. Paul Vincent G. Yu (Secretariat)',
        verified_at: '2026-02-12T11:22:00Z',
        uploaded_at: '2026-02-10T09:20:00Z'
      },
      {
        id: 'doc-app-1-3',
        application_id: 'app-001',
        requirement_id: 'doc-6-3',
        document_name: 'Barangay Council Resolution of Commendation.pdf',
        file_url: 'https://supabase-storage-placeholder/praise-documents/app-001/brgy_resolution_83a.pdf',
        file_size: 1200000,
        file_type: 'application/pdf',
        status: 'Verified',
        verification_remarks: 'Sworn Resolution No. 04 Series of 2026 on file.',
        verified_by: 'Atty. Paul Vincent G. Yu (Secretariat)',
        verified_at: '2026-02-12T11:25:00Z',
        uploaded_at: '2026-02-10T09:25:00Z'
      }
    ],
    assigned_evaluators: ['user-evaluator-1', 'user-evaluator-2'],
    evaluations: [
      {
        id: 'eval-001',
        application_id: 'app-001',
        evaluator_id: 'user-evaluator-1',
        evaluator_name: 'Engr. Manuel C. Tan (CPDO)',
        evaluator_office: 'City Planning and Development Office',
        total_raw_score: 96,
        weighted_percentage: 96.0,
        general_remarks: 'Impeccable field records and demonstrable health outcome improvements in Brgy. 83-A. Highly recommended for top distinction.',
        is_submitted: true,
        submitted_at: '2026-02-15T15:40:00Z',
        scores: [
          { id: 'sc-1', evaluation_id: 'eval-001', criterion_id: 'crit-6-1', criterion_name: 'Primary Healthcare Delivery', weight_percentage: 35, max_score: 100, score: 98, remarks: 'Superb 99.4% immunization rate' },
          { id: 'sc-2', evaluation_id: 'eval-001', criterion_id: 'crit-6-2', criterion_name: 'Emergency Response & Surveillance', weight_percentage: 25, max_score: 100, score: 95, remarks: 'Quick reporting during typhoons' },
          { id: 'sc-3', evaluation_id: 'eval-001', criterion_id: 'crit-6-3', criterion_name: 'Community Trust & Compassion', weight_percentage: 20, max_score: 100, score: 96, remarks: 'Outstanding rapport with mothers' },
          { id: 'sc-4', evaluation_id: 'eval-001', criterion_id: 'crit-6-4', criterion_name: 'Health Center Maintenance', weight_percentage: 10, max_score: 100, score: 92, remarks: 'Clean cold chain logs' },
          { id: 'sc-5', evaluation_id: 'eval-001', criterion_id: 'crit-6-5', criterion_name: 'Continuous Medical Education', weight_percentage: 10, max_score: 100, score: 94, remarks: 'Regular seminar attendance' }
        ]
      },
      {
        id: 'eval-002',
        application_id: 'app-001',
        evaluator_id: 'user-evaluator-2',
        evaluator_name: 'Carmela S. Bastes (CSWDO)',
        evaluator_office: 'City Social Welfare and Development Office',
        total_raw_score: 95,
        weighted_percentage: 95.0,
        general_remarks: 'Consistently goes beyond what is required of a volunteer health worker. Exceptional leadership in maternal healthcare.',
        is_submitted: true,
        submitted_at: '2026-02-16T10:15:00Z',
        scores: [
          { id: 'sc-6', evaluation_id: 'eval-002', criterion_id: 'crit-6-1', criterion_name: 'Primary Healthcare Delivery', weight_percentage: 35, max_score: 100, score: 96, remarks: 'Verified catchment performance' },
          { id: 'sc-7', evaluation_id: 'eval-002', criterion_id: 'crit-6-2', criterion_name: 'Emergency Response & Surveillance', weight_percentage: 25, max_score: 100, score: 94, remarks: 'Reliable alert system' },
          { id: 'sc-8', evaluation_id: 'eval-002', criterion_id: 'crit-6-3', criterion_name: 'Community Trust & Compassion', weight_percentage: 20, max_score: 100, score: 95, remarks: 'Deep community integration' },
          { id: 'sc-9', evaluation_id: 'eval-002', criterion_id: 'crit-6-4', criterion_name: 'Health Center Maintenance', weight_percentage: 10, max_score: 100, score: 95, remarks: 'Organized filing system' },
          { id: 'sc-10', evaluation_id: 'eval-002', criterion_id: 'crit-6-5', criterion_name: 'Continuous Medical Education', weight_percentage: 10, max_score: 100, score: 93, remarks: 'Updated CPR certification' }
        ]
      }
    ],
    endorsement: {
      id: 'end-001',
      application_id: 'app-001',
      endorsed_by: 'Dr. Danilo E. Ecarma',
      endorser_title: 'City Health Officer II',
      decision: 'Endorsed',
      remarks: 'Wholeheartedly endorsed. Nominee is the backbone of our maternal and child health program in District 4.',
      created_at: '2026-02-11T08:30:00Z'
    }
  },
  {
    id: 'app-002',
    application_number: 'PRAISE-2026-00002',
    award_id: 'award-1',
    award_name: 'Outstanding Work Performance Award',
    award_year: 2026,
    nominee_id: 'user-nominee-2',
    nominee_name: 'Ricardo S. Montejo',
    employee_id: 'TAC-DRRM-019',
    position_title: 'Emergency Operations Center Specialist',
    office_id: 'off-7',
    office_name: 'City Disaster Risk Reduction and Management Office',
    division_section: 'Operations and Warning Division',
    employment_category: 'Permanent',
    contact_number: '+63 908 765 4321',
    email: 'ricardo.montejo@tacloban.gov.ph',
    barangay: 'Brgy. 37 Palanog',
    nomination_type: 'Individual',
    nominator_id: 'user-admin-1',
    nominator_name: 'Ilden T. Perez',
    nominator_position: 'CDRRMO Officer',
    nominating_office: 'City Disaster Risk Reduction and Management Office',
    justification: 'Ricardo designed the Tacloban Real-Time Early Warning Mesh that connected 42 low-lying coastal barangays to the central EOC during severe weather alerts.',
    accomplishments: 'Modernized city telemetry data feeds; reduced emergency dispatch response time from 14 minutes to 6.2 minutes; IPCR rating of 4.95 (Outstanding) in the last two consecutive rating periods.',
    supporting_narrative: 'A tireless public servant who stays on 36-hour continuous duty during Red Warning weather occurrences without complaint.',
    date_of_nomination: '2026-02-12',
    status: 'Awarded',
    processing_stage: 'Awarded',
    required_action: 'Award Conferred. Official Certificate and Incentive Released.',
    final_weighted_score: 96.8,
    deliberation_remarks: 'Unanimously approved by PRAISE Committee with commendation from City Mayor.',
    deliberation_decision: 'Approved',
    deliberation_date: '2026-02-17',
    award_date: '2026-02-18',
    created_at: '2026-02-12T10:00:00Z',
    updated_at: '2026-02-18T16:00:00Z',
    documents: [
      {
        id: 'doc-app-2-1',
        application_id: 'app-002',
        requirement_id: 'doc-1-1',
        document_name: 'Accomplished PRAISE Nomination Form.pdf',
        file_url: 'https://supabase-storage-placeholder/praise-documents/app-002/nomination_form.pdf',
        file_size: 1540000,
        file_type: 'application/pdf',
        status: 'Verified',
        verification_remarks: 'Validated',
        verified_by: 'Atty. Paul Vincent G. Yu (Secretariat)',
        verified_at: '2026-02-13T10:00:00Z',
        uploaded_at: '2026-02-12T10:05:00Z'
      },
      {
        id: 'doc-app-2-2',
        application_id: 'app-002',
        requirement_id: 'doc-1-2',
        document_name: 'Certified Copy of IPCR for last 2 rating periods.pdf',
        file_url: 'https://supabase-storage-placeholder/praise-documents/app-002/ipcr_ratings.pdf',
        file_size: 3200000,
        file_type: 'application/pdf',
        status: 'Verified',
        verification_remarks: 'Average IPCR 4.95 verified by HRMDO Records',
        verified_by: 'Atty. Paul Vincent G. Yu (Secretariat)',
        verified_at: '2026-02-13T10:02:00Z',
        uploaded_at: '2026-02-12T10:10:00Z'
      }
    ],
    assigned_evaluators: ['user-evaluator-1'],
    evaluations: [
      {
        id: 'eval-003',
        application_id: 'app-002',
        evaluator_id: 'user-evaluator-1',
        evaluator_name: 'Engr. Manuel C. Tan (CPDO)',
        evaluator_office: 'City Planning and Development Office',
        total_raw_score: 97,
        weighted_percentage: 96.8,
        general_remarks: 'Groundbreaking tech innovation directly saving lives in disaster-prone coastal sectors of Tacloban.',
        is_submitted: true,
        submitted_at: '2026-02-14T16:00:00Z',
        scores: [
          { id: 'sc-11', evaluation_id: 'eval-003', criterion_id: 'crit-1-1', criterion_name: 'Quality and Consistency', weight_percentage: 30, max_score: 100, score: 98, remarks: 'Exceptional standards' },
          { id: 'sc-12', evaluation_id: 'eval-003', criterion_id: 'crit-1-2', criterion_name: 'Productivity and Impact', weight_percentage: 25, max_score: 100, score: 99, remarks: 'Reduced dispatch time by half' },
          { id: 'sc-13', evaluation_id: 'eval-003', criterion_id: 'crit-1-3', criterion_name: 'Initiative & Innovation', weight_percentage: 20, max_score: 100, score: 97, remarks: 'Telemetry mesh design' },
          { id: 'sc-14', evaluation_id: 'eval-003', criterion_id: 'crit-1-4', criterion_name: 'Customer Service', weight_percentage: 15, max_score: 100, score: 92, remarks: 'Community training sessions' },
          { id: 'sc-15', evaluation_id: 'eval-003', criterion_id: 'crit-1-5', criterion_name: 'Teamwork & Ethics', weight_percentage: 10, max_score: 100, score: 95, remarks: 'Dependable lead operator' }
        ]
      }
    ],
    endorsement: {
      id: 'end-002',
      application_id: 'app-002',
      endorsed_by: 'Ilden T. Perez',
      endorser_title: 'CDRRMO Officer',
      decision: 'Endorsed',
      remarks: 'Strongest possible endorsement for this pioneering lifesaver.',
      created_at: '2026-02-12T11:00:00Z'
    }
  },
  {
    id: 'app-003',
    application_number: 'PRAISE-2026-00003',
    award_id: 'award-5',
    award_name: 'Outstanding Barangay Nutrition Scholar (BNS)',
    award_year: 2026,
    nominee_name: 'Maria Lourdes C. Balais',
    employee_id: 'TAC-BNS-012',
    position_title: 'Barangay Nutrition Scholar',
    office_id: 'off-12',
    office_name: 'City Nutrition & Barangay Health Affairs',
    division_section: 'City Nutrition Action Division',
    employment_category: 'Barangay Worker',
    contact_number: '+63 939 123 4567',
    email: 'maria.balais@tacloban.gov.ph',
    barangay: 'Brgy. 62-B Sagkahan',
    nomination_type: 'Individual',
    nominator_id: 'user-admin-1',
    nominator_name: 'Dr. Gloria F. Fabrigas',
    nominator_position: 'City Nutrition Action Officer',
    nominating_office: 'City Nutrition & Barangay Health Affairs',
    justification: 'Achieved a remarkable 45% reduction in wasted child cases in Sagkahan district through innovative hydroponic vegetable nursery and daily feeding programs.',
    accomplishments: 'OPT Plus coverage reached 98.2%; established the first Brgy 62-B Community Feeding Kitchen funded by civic donors; zero dropouts in 120-day supplementary feeding.',
    supporting_narrative: 'Maria works tirelessly with indigent mothers in Sagkahan, conducting home cooking demonstrations for affordable nutritious food.',
    date_of_nomination: '2026-02-14',
    status: 'For Verification',
    processing_stage: 'Document Verification',
    required_action: 'Secretariat checking documentary requirements',
    created_at: '2026-02-14T08:30:00Z',
    updated_at: '2026-02-15T09:00:00Z',
    documents: [
      {
        id: 'doc-app-3-1',
        application_id: 'app-003',
        requirement_id: 'doc-5-1',
        document_name: 'Accomplished BNS Evaluation Form.pdf',
        file_url: 'https://supabase-storage-placeholder/praise-documents/app-003/bns_form.pdf',
        file_size: 1420000,
        file_type: 'application/pdf',
        status: 'For Verification',
        uploaded_at: '2026-02-14T08:40:00Z'
      },
      {
        id: 'doc-app-3-2',
        application_id: 'app-003',
        requirement_id: 'doc-5-2',
        document_name: 'Certified OPT Plus Annual Results.pdf',
        file_url: 'https://supabase-storage-placeholder/praise-documents/app-003/opt_results.pdf',
        file_size: 2100000,
        file_type: 'application/pdf',
        status: 'For Verification',
        uploaded_at: '2026-02-14T08:42:00Z'
      },
      {
        id: 'doc-app-3-3',
        application_id: 'app-003',
        requirement_id: 'doc-5-3',
        document_name: 'Barangay Nutrition Action Plan Report.pdf',
        file_url: 'https://supabase-storage-placeholder/praise-documents/app-003/bnap_report.pdf',
        file_size: 980000,
        file_type: 'application/pdf',
        status: 'For Verification',
        uploaded_at: '2026-02-14T08:45:00Z'
      }
    ],
    endorsement: {
      id: 'end-003',
      application_id: 'app-003',
      endorsed_by: 'Dr. Gloria F. Fabrigas',
      endorser_title: 'City Nutrition Action Officer',
      decision: 'Endorsed',
      remarks: 'Endorsed with full honors. Her dedication transformed malnutrition rates in Sagkahan.',
      created_at: '2026-02-14T11:30:00Z'
    }
  },
  {
    id: 'app-004',
    application_number: 'PRAISE-2026-00004',
    award_id: 'award-2',
    award_name: 'Perfect Attendance & Punctuality Award',
    award_year: 2026,
    nominee_name: 'Felipe J. Gonzaga',
    employee_id: 'TAC-CTO-088',
    position_title: 'Senior Revenue Collection Clerk',
    office_id: 'off-10',
    office_name: 'City Treasurer\'s Office',
    division_section: 'Treasury Cash & Assessment Division',
    employment_category: 'Permanent',
    contact_number: '+63 945 987 6543',
    email: 'felipe.gonzaga@tacloban.gov.ph',
    barangay: 'Brgy. 109 V&G Subdivision',
    nomination_type: 'Individual',
    nominator_id: 'user-admin-1',
    nominator_name: 'Zenaida A. Santos',
    nominator_position: 'City Treasurer',
    nominating_office: 'City Treasurer\'s Office',
    justification: 'Felipe completed 250 official workdays with zero minutes of tardiness and zero absences, managing continuous tax collection counters.',
    accomplishments: 'Maintained 100% teller window uptime during peak business permit renewal season; praised by over 500 taxpayer survey respondents for prompt service.',
    supporting_narrative: 'A model of clockwork discipline and commitment to public convenience.',
    date_of_nomination: '2026-02-15',
    status: 'For Endorsement',
    processing_stage: 'Endorsement',
    required_action: 'Head of Office Endorsement Required',
    created_at: '2026-02-15T11:00:00Z',
    updated_at: '2026-02-15T11:00:00Z',
    documents: [
      {
        id: 'doc-app-4-1',
        application_id: 'app-004',
        requirement_id: 'doc-2-1',
        document_name: 'Nomination Form with DTR Summary.pdf',
        file_url: 'https://supabase-storage-placeholder/praise-documents/app-004/dtr_summary.pdf',
        file_size: 920000,
        file_type: 'application/pdf',
        status: 'Submitted',
        uploaded_at: '2026-02-15T11:05:00Z'
      },
      {
        id: 'doc-app-4-2',
        application_id: 'app-004',
        requirement_id: 'doc-2-2',
        document_name: 'HRMDO Biometric Attendance Certification.pdf',
        file_url: 'https://supabase-storage-placeholder/praise-documents/app-004/biometric_cert.pdf',
        file_size: 1650000,
        file_type: 'application/pdf',
        status: 'Submitted',
        uploaded_at: '2026-02-15T11:10:00Z'
      }
    ]
  },
  {
    id: 'app-005',
    application_number: 'PRAISE-2026-00005',
    award_id: 'award-3',
    award_name: 'On-the-Spot Heroism & Civic Duty Award',
    award_year: 2026,
    nominee_name: 'Joel K. Alcantara',
    employee_id: 'TAC-GSO-055',
    position_title: 'Administrative Aide / Utility Specialist',
    office_id: 'off-8',
    office_name: 'City General Services Office',
    division_section: 'Building Maintenance Division',
    employment_category: 'Job Order',
    contact_number: '+63 916 432 1098',
    email: 'joel.alcantara@tacloban.gov.ph',
    barangay: 'Brgy. 48-A Fatima',
    nomination_type: 'Individual',
    nominator_id: 'user-admin-1',
    nominator_name: 'Rolando M. Gomez',
    nominator_position: 'City General Services Officer',
    nominating_office: 'City General Services Office',
    justification: 'Joel discovered a lost envelope containing PHP 185,000 cash and bank documents left by a senior citizen taxpayer in the City Hall lobby and immediately surrendered it to the City Security Unit for return.',
    accomplishments: 'Reunited the citizen with complete cash savings; earned commendation from City Council; displayed highest standard of public integrity.',
    supporting_narrative: 'Despite being a Job Order worker with modest wages, Joel acted with unwavering honesty, setting an inspirational example for all city employees.',
    date_of_nomination: '2026-02-16',
    status: 'Incomplete',
    processing_stage: 'Document Verification',
    required_action: 'Compliance: Missing Sworn Statement from Assisted Citizen',
    created_at: '2026-02-16T08:00:00Z',
    updated_at: '2026-02-16T13:00:00Z',
    documents: [
      {
        id: 'doc-app-5-1',
        application_id: 'app-005',
        requirement_id: 'doc-3-1',
        document_name: 'Incident Narrative Report & Official Blotter.pdf',
        file_url: 'https://supabase-storage-placeholder/praise-documents/app-005/blotter_report.pdf',
        file_size: 1150000,
        file_type: 'application/pdf',
        status: 'Verified',
        verification_remarks: 'City Security Blotter No. 2026-088 verified.',
        verified_by: 'Atty. Paul Vincent G. Yu (Secretariat)',
        verified_at: '2026-02-16T11:00:00Z',
        uploaded_at: '2026-02-16T08:10:00Z'
      },
      {
        id: 'doc-app-5-2',
        application_id: 'app-005',
        requirement_id: 'doc-3-2',
        document_name: 'Witness Statements / Client Commendation.pdf',
        file_url: '',
        status: 'Missing',
        verification_remarks: 'Please upload notarized citizen acknowledgment letter to complete documentary verification.',
        uploaded_at: ''
      }
    ],
    endorsement: {
      id: 'end-005',
      application_id: 'app-005',
      endorsed_by: 'Rolando M. Gomez',
      endorser_title: 'City General Services Officer',
      decision: 'Endorsed',
      remarks: 'Extraordinary honesty. Exemplifies the integrity of Tacloban City Hall staff.',
      created_at: '2026-02-16T09:30:00Z'
    }
  }
];

export const INITIAL_AUDIT_LOGS: ApplicationHistory[] = [
  {
    id: 'log-1',
    application_id: 'app-001',
    user_id: 'user-head-1',
    user_name: 'Dr. Danilo E. Ecarma',
    user_role: 'HEAD_OF_OFFICE',
    action: 'Nomination Submitted',
    previous_status: 'Draft',
    new_status: 'Submitted',
    remarks: 'Nomination for Elena M. Rodriguez submitted for Outstanding BHW',
    created_at: '2026-02-10T09:00:00Z'
  },
  {
    id: 'log-2',
    application_id: 'app-001',
    user_id: 'user-head-1',
    user_name: 'Dr. Danilo E. Ecarma',
    user_role: 'HEAD_OF_OFFICE',
    action: 'Head of Office Endorsed Application',
    previous_status: 'Submitted',
    new_status: 'Endorsed',
    remarks: 'Endorsement letter signed and forwarded to PRAISE Secretariat',
    created_at: '2026-02-11T08:30:00Z'
  },
  {
    id: 'log-3',
    application_id: 'app-001',
    user_id: 'user-secretariat-1',
    user_name: 'Atty. Paul Vincent G. Yu',
    user_role: 'SECRETARIAT',
    action: 'Secretariat Verified All Documents',
    previous_status: 'For Verification',
    new_status: 'Verified',
    remarks: 'All 3 mandatory documents verified with CHO records. Application routed to Evaluators.',
    created_at: '2026-02-12T11:30:00Z'
  },
  {
    id: 'log-4',
    application_id: 'app-001',
    user_id: 'user-evaluator-1',
    user_name: 'Engr. Manuel C. Tan',
    user_role: 'EVALUATOR',
    action: 'Evaluator Submitted Assessment',
    previous_status: 'Under Evaluation',
    new_status: 'Evaluation Completed',
    remarks: 'Evaluation submitted with weighted score 96.0%. Locked.',
    created_at: '2026-02-15T15:40:00Z'
  },
  {
    id: 'log-5',
    application_id: 'app-002',
    user_id: 'user-admin-1',
    user_name: 'Marites S. Bocar',
    user_role: 'ADMINISTRATOR',
    action: 'Final Decision Approved & Award Conferred',
    previous_status: 'For Deliberation',
    new_status: 'Awarded',
    remarks: 'PRAISE Resolution No. 2026-01 adopted. Certificate and official monetary incentive prepared.',
    created_at: '2026-02-18T16:00:00Z'
  }
];

export const INITIAL_NOTIFICATIONS: InAppNotification[] = [
  {
    id: 'notif-1',
    target_role: 'SECRETARIAT',
    application_id: 'app-003',
    application_number: 'PRAISE-2026-00003',
    title: 'New Nomination for Verification',
    message: 'Nomination for Maria Lourdes C. Balais (Brgy. 62-B) has been endorsed and is awaiting document verification.',
    is_read: false,
    created_at: '2026-02-14T11:35:00Z',
    link_tab: 'verification'
  },
  {
    id: 'notif-2',
    target_role: 'HEAD_OF_OFFICE',
    application_id: 'app-004',
    application_number: 'PRAISE-2026-00004',
    title: 'Nomination Endorsement Required',
    message: 'Felipe J. Gonzaga (City Treasurer\'s Office) requires your official Head of Office endorsement.',
    is_read: false,
    created_at: '2026-02-15T11:05:00Z',
    link_tab: 'endorsements'
  },
  {
    id: 'notif-3',
    target_role: 'NOMINEE',
    user_id: 'user-nominee-1',
    application_id: 'app-001',
    application_number: 'PRAISE-2026-00001',
    title: 'Evaluations Completed',
    message: 'Your Outstanding BHW nomination evaluations have been completed and routed for PRAISE Committee Deliberation.',
    is_read: false,
    created_at: '2026-02-16T14:30:00Z',
    link_tab: 'my-applications'
  },
  {
    id: 'notif-4',
    target_role: 'NOMINEE',
    application_id: 'app-005',
    application_number: 'PRAISE-2026-00005',
    title: 'Document Compliance Needed',
    message: 'Document verification returned "Incomplete". Please upload the missing Witness Sworn Statement.',
    is_read: false,
    created_at: '2026-02-16T13:05:00Z',
    link_tab: 'my-applications'
  },
  {
    id: 'notif-5',
    target_role: 'ADMINISTRATOR',
    application_id: 'app-001',
    application_number: 'PRAISE-2026-00001',
    title: 'Deliberation Ready',
    message: 'Candidate Elena M. Rodriguez (Outstanding BHW) achieved a 95.5% weighted score and is ready for committee resolution.',
    is_read: false,
    created_at: '2026-02-16T14:45:00Z',
    link_tab: 'deliberation'
  }
];

export const TACLOBAN_BARANGAYS = [
  'Brgy. 1 Jones', 'Brgy. 2 Libertador', 'Brgy. 3 Real', 'Brgy. 4 Lopez Jaena', 'Brgy. 5 Justice Romualdez',
  'Brgy. 10 Burgos', 'Brgy. 20 Zamora', 'Brgy. 37 Palanog', 'Brgy. 48-A Fatima', 'Brgy. 54-A Magallanes',
  'Brgy. 62-B Sagkahan', 'Brgy. 74 Nula-Tula', 'Brgy. 83-A San Jose (Cura)', 'Brgy. 88 San Jose',
  'Brgy. 91 Abucay', 'Brgy. 95-A Caibaan', 'Brgy. 99 Diit', 'Brgy. 109 V&G Subdivision', 'Brgy. 110 Utap',
  'Brgy. Tagapuro', 'Brgy. New Kawayan', 'Brgy. Sto. Niño', 'Brgy. Suhi', 'Brgy. San Roque'
];
